/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MacawHeader {
        /**
          * Returns the current settings.
          * @returns
         */
        "getSettings": () => Promise<{
            height: number;
            sticky: boolean;
            visible: boolean;
        }>;
        /**
          * Change the settings of the Macaw Header Component, returns the current settings.
          * @param settings
          * @returns
         */
        "setSettings": (settings: any) => Promise<{
            height: number;
            sticky: boolean;
            visible: boolean;
        }>;
        "sticky": boolean;
        "transitionStyle": "slide" | "fade";
        "visibility": "always" | "to-top" | "hidden";
        "visible": boolean;
    }
}
declare global {
    interface HTMLMacawHeaderElement extends Components.MacawHeader, HTMLStencilElement {
    }
    var HTMLMacawHeaderElement: {
        prototype: HTMLMacawHeaderElement;
        new (): HTMLMacawHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "macaw-header": HTMLMacawHeaderElement;
    }
}
declare namespace LocalJSX {
    interface MacawHeader {
        "onMwcHeaderHeight"?: (event: CustomEvent<object>) => void;
        "onMwcHeaderInit"?: (event: CustomEvent<object>) => void;
        "onMwcHeaderSticky"?: (event: CustomEvent<object>) => void;
        "onMwcHeaderVisible"?: (event: CustomEvent<object>) => void;
        "sticky"?: boolean;
        "transitionStyle"?: "slide" | "fade";
        "visibility"?: "always" | "to-top" | "hidden";
        "visible"?: boolean;
    }
    interface IntrinsicElements {
        "macaw-header": MacawHeader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "macaw-header": LocalJSX.MacawHeader & JSXBase.HTMLAttributes<HTMLMacawHeaderElement>;
        }
    }
}
