/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ToucanHeader {
        /**
          * Returns the current settings.
          * @returns
         */
        "getSettings": () => Promise<{
            height: number;
            sticky: boolean;
            visible: boolean;
        }>;
        /**
          * Change the settings of the Toucan Header Component, returns the current settings.
          * @param settings
          * @returns
         */
        "setSettings": (settings: any) => Promise<{
            height: number;
            sticky: boolean;
            visible: boolean;
        }>;
        "sticky": boolean;
        "transitionStyle": "slide" | "fade";
        "visibility": "always" | "to-top" | "hidden";
        "visible": boolean;
    }
}
declare global {
    interface HTMLToucanHeaderElement extends Components.ToucanHeader, HTMLStencilElement {
    }
    var HTMLToucanHeaderElement: {
        prototype: HTMLToucanHeaderElement;
        new (): HTMLToucanHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "toucan-header": HTMLToucanHeaderElement;
    }
}
declare namespace LocalJSX {
    interface ToucanHeader {
        "onTwcHeaderHeight"?: (event: CustomEvent<object>) => void;
        "onTwcHeaderInit"?: (event: CustomEvent<object>) => void;
        "onTwcHeaderSticky"?: (event: CustomEvent<object>) => void;
        "onTwcHeaderVisible"?: (event: CustomEvent<object>) => void;
        "sticky"?: boolean;
        "transitionStyle"?: "slide" | "fade";
        "visibility"?: "always" | "to-top" | "hidden";
        "visible"?: boolean;
    }
    interface IntrinsicElements {
        "toucan-header": ToucanHeader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "toucan-header": LocalJSX.ToucanHeader & JSXBase.HTMLAttributes<HTMLToucanHeaderElement>;
        }
    }
}
