/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TwcHeader {
        /**
          * Returns the current settings.
          * @returns
         */
        "getSettings": () => Promise<{
            height: number;
            sticky: boolean;
            visible: boolean;
        }>;
        /**
          * Change the settings of the Toucan Header Component, returns the current settings.
          * @param settings
          * @returns
         */
        "setSettings": (settings: any) => Promise<{
            height: number;
            sticky: boolean;
            visible: boolean;
        }>;
        "sticky": boolean;
        "transitionStyle": "slide" | "fade";
        "visibility": "always" | "to-top" | "hidden";
        "visible": boolean;
    }
}
declare global {
    interface HTMLTwcHeaderElement extends Components.TwcHeader, HTMLStencilElement {
    }
    var HTMLTwcHeaderElement: {
        prototype: HTMLTwcHeaderElement;
        new (): HTMLTwcHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "twc-header": HTMLTwcHeaderElement;
    }
}
declare namespace LocalJSX {
    interface TwcHeader {
        "onTwcHeaderHeight"?: (event: CustomEvent<object>) => void;
        "onTwcHeaderInit"?: (event: CustomEvent<object>) => void;
        "onTwcHeaderSticky"?: (event: CustomEvent<object>) => void;
        "onTwcHeaderVisible"?: (event: CustomEvent<object>) => void;
        "sticky"?: boolean;
        "transitionStyle"?: "slide" | "fade";
        "visibility"?: "always" | "to-top" | "hidden";
        "visible"?: boolean;
    }
    interface IntrinsicElements {
        "twc-header": TwcHeader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "twc-header": LocalJSX.TwcHeader & JSXBase.HTMLAttributes<HTMLTwcHeaderElement>;
        }
    }
}
